name: FORCE TRANSLATE
on:
  workflow_dispatch:
  repository_dispatch:
    types: [force_translation]

concurrency:
  group: translate
  cancel-in-progress: true

jobs:
  translate:
    runs-on: ubuntu-latest
    env:
      WEGLOT_API_KEY: ${{secrets.WEGLOT_API_KEY}}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Install dependencies
        run: |
          cd ./translation-scripts
          npm install -g pnpm && pnpm install
      - run: |
          cd ./translation-scripts
          FORCE_TRANSLATE=true npm run translate
      - name: Commit changes
        uses: EndBug/add-and-commit@v7
        with:
          author_name: translate-bot
          author_email: mail@example.com
          message: "(translate)"
          add: "."
